# Generated by Django 5.1.7 on 2025-03-23 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsAccounts', '0002_alter_job_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['priority_level', 'deadline'], name='jobsAccount_priorit_6a6991_idx'),
        ),
    ]
