# Generated by Django 5.1.7 on 2025-03-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsAccounts', '0003_job_jobsaccount_priorit_6a6991_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_job_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_job_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='wait_time',
            field=models.IntegerField(default=0),
        ),
    ]
